name: tomogui
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyqt=5
  - matplotlib>=3.5.0
  - numpy>=1.20.0,<1.27
  - pillow>=8.0.0
  - h5py>=3.0.0
  - pyqtgraph>=0.12.0
  - pip
  - pip:
    - -e .